# Baseline results

In [ ]:
import os
import random
import warnings
from dotenv import load_dotenv
from rich import pretty, print, traceback
from tqdm import tqdm

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
traceback.install(show_locals=True)
pretty.install()
load_dotenv();

In [14]:
positive_class = "Pneumonia"

## Load model

In [15]:
from model_chexagent.chexagent import CheXagent
chexagent = CheXagent()

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████| 3/3 [00:02<00:00,  1.00it/s]

## Load dataset

In [16]:
from datasets import load_dataset, Dataset
ds: Dataset = load_dataset("vllm-pneumonia-detection/mimic-500-gt", split="test")
image_root_path = "/home/nicoleg/physionet.org/files/mimic-cxr-jpg/2.0.0/"

def in_domain(sample):
    label = sample[positive_class]
    return label == 0 or label == 1

def set_image_path(sample):
    sample["image_files"] = image_root_path + sample["image_files"]
    return sample

ds = ds.filter(in_domain)
ds = ds.map(set_image_path)

Map: 100%|██████████| 89/89 [00:00<00:00, 2503.41 examples/s]

In [17]:
sample = random.choice(ds)
print(sample)

{
    'dicom_id': '3ced14b8-2accf862-b2eab013-efdf4f2d-991f75eb',
    'split': 'test',
    'study_id': '56264253',
    'subject_id': '14841168',
    'image_files':
'/home/nicoleg/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p14/p14841168/s56264253/3ced14b8-2accf862-b2eab013-efd
f4f2d-991f75eb.jpg',
    'reports': '                                 FINAL REPORT\n INDICATION:  ___-year-old female with hypercapnic
respiratory failure.\n \n COMPARISON:  ___.\n \n PORTABLE CHEST:\n \n Endotracheal tube terminates 4.3 cm above the
carina.  Nasogastric tube passes\n into the stomach.  There is a left-sided hemodialysis catheter, which extends\n
to the low SVC.\n \n Lung volumes remain low.  There are bilateral pleural effusions, increased. \n There is
diffuse hazy parenchymal opacity, most compatible with pulmonary\n edema in the setting of central vascular
congestion and cardiomegaly.  There\n is no new focal opacity to suggest pneumonia.  There is no pneumothorax.\n \n
IMPRESSION:  Interval worsening of pulmonary edema compared to one day prior. \n Pleural effusions also increased.
No pneumonia.\n',
    'Atelectasis': -2.0,
    'Cardiomegaly': -2.0,
    'Consolidation': -2.0,
    'Edema': 1.0,
    'Enlarged Cardiomediastinum': -2.0,
    'Fracture': -2.0,
    'Lung Lesion': -2.0,
    'Lung Opacity': -2.0,
    'No Finding': -2.0,
    'Effusion': 1.0,
    'Pleural Other': -2.0,
    'Pneumonia': 0.0,
    'Pneumothorax': -2.0,
    'Support Devices': -2.0
}

# Get results

In [18]:
results = {}
yes_no = {"yes": 1, "no": 0}
for sample in tqdm(ds.shuffle(seed=42)):
    dicom_id = sample["dicom_id"]
    path = sample["image_files"]
    response = chexagent.binary_disease_classification([path], positive_class).lower()
    ypred = yes_no[response]
    results[dicom_id] = {
        "y_true": sample[positive_class],
        "y_pred": ypred,
        "report": sample["reports"],
        "image_files": path,
    }

  0%|          | 0/89 [00:00<?, ?it/s]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 1/89 [00:02<04:14,  2.89s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 2/89 [00:04<02:46,  1.92s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 3/89 [00:05<02:16,  1.58s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 4/89 [00:06<01:59,  1.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  6%|▌         | 5/89 [00:07<01:50,  1.32s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  7%|▋         | 6/89 [00:08<01:45,  1.27s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  8%|▊         | 7/89 [00:09<01:41,  1.24s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  9%|▉         | 8/89 [00:11<01:39,  1.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 10%|█         | 9/89 [00:12<01:37,  1.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 11%|█         | 10/89 [00:13<01:35,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 12%|█▏        | 11/89 [00:14<01:33,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 13%|█▎        | 12/89 [00:15<01:31,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 15%|█▍        | 13/89 [00:17<01:30,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 16%|█▌        | 14/89 [00:18<01:28,  1.18s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 17%|█▋        | 15/89 [00:19<01:28,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 18%|█▊        | 16/89 [00:20<01:26,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 19%|█▉        | 17/89 [00:21<01:25,  1.18s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 20%|██        | 18/89 [00:23<01:24,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 21%|██▏       | 19/89 [00:24<01:22,  1.18s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 22%|██▏       | 20/89 [00:25<01:22,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 24%|██▎       | 21/89 [00:26<01:21,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 25%|██▍       | 22/89 [00:27<01:20,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 26%|██▌       | 23/89 [00:29<01:18,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 27%|██▋       | 24/89 [00:30<01:17,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 28%|██▊       | 25/89 [00:31<01:15,  1.18s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 29%|██▉       | 26/89 [00:32<01:15,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 30%|███       | 27/89 [00:33<01:14,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 31%|███▏      | 28/89 [00:35<01:13,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 33%|███▎      | 29/89 [00:36<01:11,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 34%|███▎      | 30/89 [00:37<01:10,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 35%|███▍      | 31/89 [00:38<01:09,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 36%|███▌      | 32/89 [00:39<01:08,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 37%|███▋      | 33/89 [00:40<01:06,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 38%|███▊      | 34/89 [00:42<01:05,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 39%|███▉      | 35/89 [00:43<01:04,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 40%|████      | 36/89 [00:44<01:02,  1.18s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 42%|████▏     | 37/89 [00:45<01:02,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 43%|████▎     | 38/89 [00:46<01:01,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 44%|████▍     | 39/89 [00:48<00:59,  1.19s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 45%|████▍     | 40/89 [00:49<00:58,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 46%|████▌     | 41/89 [00:50<00:57,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 47%|████▋     | 42/89 [00:51<00:57,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 48%|████▊     | 43/89 [00:53<00:56,  1.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 49%|████▉     | 44/89 [00:54<00:54,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 51%|█████     | 45/89 [00:55<00:53,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 52%|█████▏    | 46/89 [00:56<00:52,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 53%|█████▎    | 47/89 [00:57<00:50,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 54%|█████▍    | 48/89 [00:59<00:49,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 55%|█████▌    | 49/89 [01:00<00:48,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 56%|█████▌    | 50/89 [01:01<00:46,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 57%|█████▋    | 51/89 [01:02<00:45,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 58%|█████▊    | 52/89 [01:03<00:44,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 60%|█████▉    | 53/89 [01:05<00:43,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 61%|██████    | 54/89 [01:06<00:42,  1.20s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 62%|██████▏   | 55/89 [01:07<00:41,  1.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 63%|██████▎   | 56/89 [01:08<00:40,  1.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 64%|██████▍   | 57/89 [01:10<00:39,  1.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 65%|██████▌   | 58/89 [01:11<00:38,  1.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 66%|██████▋   | 59/89 [01:12<00:36,  1.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 67%|██████▋   | 60/89 [01:13<00:35,  1.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 69%|██████▊   | 61/89 [01:14<00:34,  1.23s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 70%|██████▉   | 62/89 [01:16<00:32,  1.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 71%|███████   | 63/89 [01:17<00:31,  1.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 72%|███████▏  | 64/89 [01:18<00:30,  1.21s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 73%|███████▎  | 65/89 [01:19<00:29,  1.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 74%|███████▍  | 66/89 [01:21<00:28,  1.22s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [19]:
import pandas as pd

if "results.csv" in os.listdir("./"):
    df = pd.read_csv("results.csv", index_col="dicom_id")
else:
    df = pd.DataFrame.from_dict(results, orient="index")
    df.index.name = "dicom_id"
    df.to_csv("results.csv")

df

,y_true,y_pred,report,image_files
dicom_id,,,,
4a5bbca6-64ed6abf-84645068-6a7688bd-9a9910d4,1.0,1,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
7b43b8ff-190d3ca9-03cfbbd3-45ad3d0d-72d06c1c,1.0,0,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
463d2a28-b411bb98-f7bda38e-7030ebb9-74a8a1e0,0.0,0,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
a6a6000b-26fecffe-b90ded19-73b8a48f-6e3f7557,0.0,0,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
0cdfb937-27e0834d-4d8d1c40-cee9e187-98390c95,0.0,0,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
...,...,...,...,...
7f83f5d5-3afe2911-3b666b80-5dbde6e1-f2a9d980,0.0,0,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
6a7b83c9-7b7c6ba9-09d85de8-a76f1aa7-4fd0e047,1.0,1,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
54a9e5bc-2d3b9e9a-43c44b54-7c16e7b1-f923f86c,1.0,1,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
805c8f03-c6d068dd-c95f546c-e1dfe872-324866d0,1.0,1,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
3ced14b8-2accf862-b2eab013-efdf4f2d-991f75eb,0.0,0,FINAL REPORT\...,/home/nicoleg/physionet.org/files/mimic-cxr-jp...

In [22]:
y_true = df["y_true"].values
y_pred = df["y_pred"].values
target_names = [f"No {positive_class}", positive_class]


def generate_classification_report(
    y_true, y_pred, target_names=[f"No Pneumonia", "Pneumonia"]
):
    """
    Generate a classification report and confusion matrix.

    Parameters:
    -----------
    y_true : array-like
        True labels
    y_pred : array-like
        Predicted labels
    target_names : list
        List of class names

    Returns:
    --------
    cr : dict
        Classification report as a dictionary
    """
    from sklearn.metrics import classification_report, confusion_matrix
    from tabulate import tabulate

    # Classification report
    cr_string = classification_report(y_true, y_pred, target_names=target_names)
    cr = classification_report(
        y_true, y_pred, target_names=target_names, output_dict=True
    )
    print("Classification Report:")
    print(cr_string)

    # Confusion matrix
    print("Confusion Matrix:")
    cfm = confusion_matrix(y_true, y_pred)
    print(
        tabulate(
            cfm, headers=target_names, showindex=target_names, tablefmt="rounded_grid"
        )
    )
    return cr


cr = generate_classification_report(
    y_true,
    y_pred,
    target_names=target_names,
)

Classification Report:

              precision    recall  f1-score   support

No Pneumonia       0.77      0.93      0.85        59
   Pneumonia       0.78      0.47      0.58        30

    accuracy                           0.78        89
   macro avg       0.78      0.70      0.71        89
weighted avg       0.78      0.78      0.76        89

Confusion Matrix:

╭──────────────┬────────────────┬─────────────╮
│              │   No Pneumonia │   Pneumonia │
├──────────────┼────────────────┼─────────────┤
│ No Pneumonia │             55 │           4 │
├──────────────┼────────────────┼─────────────┤
│ Pneumonia    │             16 │          14 │
╰──────────────┴────────────────┴─────────────╯

In [23]:
summary = pd.DataFrame(
    {
        "f1-score": round(cr["macro avg"]["f1-score"], 4),
        # "roc auc": round(roc_auc_score(y_true, y_pred), 4),
        "sensitivity": round(cr["Pneumonia"]["recall"], 4),
        "specificity": round(cr["No Pneumonia"]["recall"], 4),
        "recall": round(cr["macro avg"]["recall"], 4),
        "precision": round(cr["macro avg"]["precision"], 4),
        "accuracy": round(cr["accuracy"], 4),
    },
    index=["chexagent"],
)
summary

           f1-score  sensitivity  specificity  recall  precision  accuracy
chexagent    0.7147       0.4667       0.9322  0.6994     0.7762    0.7753